version: "3.8"

services:
  prixagent-ai:
    image: prixagent-ai-wgtxm0
    container_name: prixagent-ai-container
    restart: unless-stopped

    # Configuración de logging optimizada para evitar tail inotify
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "prixagent"

    # Configuración de límites del sistema
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      nproc:
        soft: 65536
        hard: 65536

    # Variables de entorno para optimización
    environment:
      - NODE_ENV=production
      - WATCHMAN_DISABLE=true
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
      - NODE_OPTIONS=--max-old-space-size=4096 --max-http-header-size=80000
      - UV_THREADPOOL_SIZE=128
      - NODE_NO_WARNINGS=1

    # Configuración de red
    ports:
      - "3000:3000"
      - "3004:3004"

    # Configuración de recursos
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

    # Configuración adicional para evitar tail inotify
    sysctls:
      - fs.file-max=65536
      - fs.inotify.max_user_watches=524288
      - fs.inotify.max_user_instances=256
